channels:
  - conda-forge
dependencies:
  # for jupyter-desktop-server
  - websockify

  # language runtimes
  - python=3.8.*

  - numpy
  - scipy
  - matplotlib
  - pandas
  - seaborn
  - sympy
  - networkx
  - scikit-learn
  - beautifulsoup4
  - statsmodels
  - nltk
  - spacy
  - geopandas
  # From https://github.com/utoronto-2i2c/jupyterhub-deploy/issues/29
  - astroquery
  - astropy
  - galpy

  - pip<20.3

  - pip:
    # Infrastructure things
    - jupyterlab==2.*
    - voila==0.2.3
    - nbgitpuller==0.9.*
    - jupyter-resource-usage==0.5.1
    - jupytext==1.6.*
    - RISE==5.6.1
    - jupyter_contrib_nbextensions==0.5.1
    - jupyter-desktop-server==0.1.3
    - git-credential-helpers==0.2
    - notebook==6.1.6
    - jupyterhub==1.3.0
    - jupyter-server-proxy==3.1.0
    - jupyter-rsession-proxy==1.4
    - jupyter-shiny-proxy==1.1
    - jupyter-tree-download==1.0.1
    - ipywidgets==7.6.2
    # This is temporary (ref: https://github.com/utoronto-2i2c/jupyterhub-deploy/issues/77)
    - jedi==0.17.2

    - datascience
    - geojson
    - folium
    - geopy
    - otter-grader==3.1.4

    # nbextensions
    - jupyterthemes==0.20.0
    - qgrid==1.3.1
